2024-11-21 08:05:10,909 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "X:\01._Urban\#_Repeat\04_Repeat_11.11.24\12_Module_#12\module_12_4\module_12_4.py", line 26, in test_run
    rnr = runner.Runner(12, 10)
  File "X:\01._Urban\#_Repeat\04_Repeat_11.11.24\12_Module_#12\module_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-21 08:05:10,996 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "X:\01._Urban\#_Repeat\04_Repeat_11.11.24\12_Module_#12\module_12_4\module_12_4.py", line 15, in test_walk
    run = runner.Runner('Mick',  -10)
  File "X:\01._Urban\#_Repeat\04_Repeat_11.11.24\12_Module_#12\module_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
